# A github workflow which runs the pre-commit configured for the project.
name: pre-submit

on:
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags
          ref: ${{ github.head_ref }} # Checks out the PR branch

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      #----------------------------------------------
      #  -----  install & configure uv  -----
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Load cached venv
        id: cached-uv-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/uv.lock') }}

      - name: Install dependencies
        if: steps.cached-uv-dependencies.outputs.cache-hit != 'true'
        run: uv sync --extra dev

      - name: Get Changed Files
        id: files
        run: |
          files=$(git diff --name-only refs/remotes/origin/${{ github.base_ref }} | sed 's/ /\\ /g'| xargs)
          echo "Changed files: '${files}'"
          echo "list=${files}" >> $GITHUB_OUTPUT

      - name: Run pre-commit on Changed Files
        run: uv run pre-commit run --files ${{ steps.files.outputs.list }}
